version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Uploading the build output to S3...
      # No need to zip the files
artifacts:
  base-directory: '.' # Directory to collect files from
  files:
    - '**/*' # Include all files and subdirectories
