version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Packaging application for Elastic Beanstalk...
      - zip -r application.zip . # Package the entire directory into application.zip

artifacts:
  files:
    - application.zip
